# To deploy:
# -----
#   kubectl apply -f k8s.yaml
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario2
  selfLink: /api/v1/namespaces/default/pods/scenario2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scenario2
      component: webapi
  template:
    metadata:
      labels:
        app: scenario2
        component: webapi
    spec:
      containers:
        - name: testapp
          image: mjrousos/diagnostics-scenario2:1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
---
  
apiVersion: v1
kind: Service
metadata:
  name: scenario2-gateway
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: scenario2
    component: webapi
  type: LoadBalancer